services:
  db:
    image: postgres:latest
    volumes:
      - ./data/db/data:/var/lib/postgresql/data
    env_file:
      - ./dotenv_files/.env
    restart: always
  web:
    build: .
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./project:/project
      - ./data/web/static:/data/web/static
      - ./data/web/media:/data/web/media
    env_file:
      - ./dotenv_files/.env
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
  nginx:
    build: ./nginx
    volumes:
      - ./data/web/static:/data/web/static
      - ./data/web/media:/data/web/media
    ports:
      - "1337:80"
    depends_on:
      - web