services:
  db:
    image: postgres:latest
    volumes:
      - ./data/db/data:/var/lib/postgresql/data
    env_file:
      - ./dotenv_files/.env
    restart: always
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
      # - python manage.py collectstatic --noinput
      # - python manage.py makemigrations --noinput
      # - python manage.py migrate --noinput
    volumes:
      - ./project:/project
      - ./data/web/static:/data/web/static
      - ./data/web/media:/data/web/media
    env_file:
      - ./dotenv_files/.env
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db